In [1]:
import pandas as pd

df_amazon = pd.read_csv('Datasets/amazon_prime_titles.csv')
#separo las columnas que voy a utilizar en cada dataframe
df_amazon_columns = df_amazon[['title','type','release_year','cast','duration','listed_in']]
df_amazon_columns['plataforma'] = 'Amazon'
df_amazon_columns

C:\Users\Danti\AppData\Local\Temp\ipykernel_14856\635727871.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_amazon_columns['plataforma'] = 'Amazon'

,title,type,release_year,cast,duration,listed_in,plataforma
0,The Grand Seduction,Movie,2014,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",113 min,"Comedy, Drama",Amazon
1,Take Care Good Night,Movie,2018,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",110 min,"Drama, International",Amazon
2,Secrets of Deception,Movie,2017,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",74 min,"Action, Drama, Suspense",Amazon
3,Pink: Staying True,Movie,2014,"Interviews with: Pink, Adele, Beyoncé, Britney...",69 min,Documentary,Amazon
4,Monster Maker,Movie,1989,"Harry Dean Stanton, Kieran O'Brien, George Cos...",45 min,"Drama, Fantasy",Amazon
...,...,...,...,...,...,...,...
9663,Pride Of The Bowery,Movie,1940,"Leo Gorcey, Bobby Jordan",60 min,Comedy,Amazon
9664,Planet Patrol,TV Show,2018,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",4 Seasons,TV Shows,Amazon
9665,Outpost,Movie,2008,"Ray Stevenson, Julian Wadham, Richard Brake, M...",90 min,Action,Amazon
9666,Maradona: Blessed Dream,TV Show,2021,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",1 Season,"Drama, Sports",Amazon
9667,Harry Brown,Movie,2010,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",103 min,"Action, Drama, Suspense",Amazon

In [2]:
df_disneyplus = pd.read_csv('./Datasets/disney_plus_titles.csv')

df_disneyplus_columns = df_disneyplus[['title','type','release_year','cast','duration','listed_in']]
df_disneyplus_columns['plataforma'] = 'Disney Plus'
df_disneyplus_columns

C:\Users\Danti\AppData\Local\Temp\ipykernel_14856\2701461891.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_disneyplus_columns['plataforma'] = 'Disney Plus'

,title,type,release_year,cast,duration,listed_in,plataforma
0,Duck the Halls: A Mickey Mouse Christmas Special,Movie,2016,"Chris Diamantopoulos, Tony Anselmo, Tress MacN...",23 min,"Animation, Family",Disney Plus
1,Ernest Saves Christmas,Movie,1988,"Jim Varney, Noelle Parker, Douglas Seale",91 min,Comedy,Disney Plus
2,Ice Age: A Mammoth Christmas,Movie,2011,"Raymond Albert Romano, John Leguizamo, Denis L...",23 min,"Animation, Comedy, Family",Disney Plus
3,The Queen Family Singalong,Movie,2021,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",41 min,Musical,Disney Plus
4,The Beatles: Get Back,TV Show,2021,"John Lennon, Paul McCartney, George Harrison, ...",1 Season,"Docuseries, Historical, Music",Disney Plus
...,...,...,...,...,...,...,...
1445,X-Men Origins: Wolverine,Movie,2009,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...",108 min,"Action-Adventure, Family, Science Fiction",Disney Plus
1446,Night at the Museum: Battle of the Smithsonian,Movie,2009,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...",106 min,"Action-Adventure, Comedy, Family",Disney Plus
1447,Eddie the Eagle,Movie,2016,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...",107 min,"Biographical, Comedy, Drama",Disney Plus
1448,Bend It Like Beckham,Movie,2003,"Parminder Nagra, Keira Knightley, Jonathan Rhy...",112 min,"Buddy, Comedy, Coming of Age",Disney Plus
1449,Captain Sparky vs. The Flying Saucers,Movie,2012,Charlie Tahan,2 min,"Action-Adventure, Animals & Nature, Animation",Disney Plus

In [3]:
df_hulu = pd.read_csv('./Datasets/hulu_titles.csv')

df_hulu_columns = df_hulu[['title','type','release_year','cast','duration','listed_in']]
df_hulu_columns['plataforma'] = 'Hulu'

C:\Users\Danti\AppData\Local\Temp\ipykernel_14856\1845169351.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hulu_columns['plataforma'] = 'Hulu'

In [4]:
df_netflix = pd.read_json('./Datasets/netflix_titles.json')

df_netflix_columns = df_netflix[['title','type','release_year','cast','duration','listed_in']]
df_netflix_columns['plataforma'] = 'Netflix'

C:\Users\Danti\AppData\Local\Temp\ipykernel_14856\2621494281.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_netflix_columns['plataforma'] = 'Netflix'

In [5]:
#concateno todos los dataframes en una sola tabla
df_unificado = pd.concat([df_amazon_columns,df_disneyplus_columns,df_hulu_columns,df_netflix_columns],ignore_index=True)

#creo una columna para los indicies
df_unificado['indice'] = df_unificado.index

#verifico las columnas que tienen nulos
df_unificado.isnull().sum()

title              0
type               0
release_year       0
cast            5321
duration         482
listed_in          0
plataforma         0
indice             0
dtype: int64

In [6]:
#reemplazamos los valores nulos en la columna cast por 'sin dato' porque no tengo forma de rellenar una cantidad significativa de datos en esta columna
df_unificado['cast'].fillna('sin dato',inplace=True)

#decidi cambiar los nombres para que sean mas intuitivos y en español
column_names = {'title':'titulo','type' : 'clasificacion', 'release_year' : 'fecha_de_estreno','cast' : 'elenco', 'duration' : 'duracion', 'listed_in' : 'lista_de_generos'}
df_unificado.rename(columns=column_names,inplace=True)

In [7]:
#voy a analizar la columna duracion para ver si puedo hacer algo para llenar los espacio vacios
#tengo este dato como "cantidad de tiempo" y "minutos o season" asi que las separo en dos, una con numeros y otra con string
df_duracion = df_unificado["duracion"].str.split(expand=True)
df_unificado['duracion_cantidad']=df_duracion[0]
df_unificado['duracion_minOSeason']=df_duracion[1]

In [8]:
#cambio el orden de las columnas para que sea mas comodo
df_unificado = df_unificado[['indice','titulo','clasificacion','fecha_de_estreno','elenco','duracion','duracion_cantidad','duracion_minOSeason','lista_de_generos','plataforma']]

In [9]:
df_unificado.head()

,indice,titulo,clasificacion,fecha_de_estreno,elenco,duracion,duracion_cantidad,duracion_minOSeason,lista_de_generos,plataforma
0,0,The Grand Seduction,Movie,2014,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",113 min,113,min,"Comedy, Drama",Amazon
1,1,Take Care Good Night,Movie,2018,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",110 min,110,min,"Drama, International",Amazon
2,2,Secrets of Deception,Movie,2017,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",74 min,74,min,"Action, Drama, Suspense",Amazon
3,3,Pink: Staying True,Movie,2014,"Interviews with: Pink, Adele, Beyoncé, Britney...",69 min,69,min,Documentary,Amazon
4,4,Monster Maker,Movie,1989,"Harry Dean Stanton, Kieran O'Brien, George Cos...",45 min,45,min,"Drama, Fantasy",Amazon

In [10]:
# verifico todos los maximos para ver si me conviene reemplazar valores por media,mediana,etc
max_lists = df_unificado.loc[df_unificado['duracion_minOSeason'] == 'min'][['plataforma','fecha_de_estreno','duracion_cantidad']]
#primero tome los valores que son estan en minutos, si la unidad es min entonces no es nulo el dato
max_lists['duracion_cantidad'] = max_lists['duracion_cantidad'].astype('int64')
max_lists = max_lists.groupby(['plataforma','fecha_de_estreno'])['duracion_cantidad'].max()
print(max_lists['Amazon'].sort_values()) #este es un ejemplo
#hay numeros muy variados de datos por lo que sacar un promedio no seria representativo, prefiero dejarlo como 'sin dato' para que al menos figure como un dato a cambiar en el futuro en el hipotetico caso en el que se revisaran los datos.
#ademas de que no aportan nada para las consultas que piden los enunciados
df_unificado.fillna('sin dato',inplace=True)

fecha_de_estreno
1926     60
1927     65
1920     78
1935     83
1934     84
       ...
2019    540
2014    541
2016    541
2017    550
2018    601
Name: duracion_cantidad, Length: 100, dtype: int64

In [11]:
df_unificado.loc[df_unificado['duracion_minOSeason'] == 'sin dato']

,indice,titulo,clasificacion,fecha_de_estreno,elenco,duracion,duracion_cantidad,duracion_minOSeason,lista_de_generos,plataforma
11118,11118,Ricky Velez: Here's Everything,Movie,2021,sin dato,sin dato,sin dato,sin dato,"Comedy, Stand Up",Hulu
11130,11130,Out of the Shadows: The Man Behind the Steele ...,Movie,2021,sin dato,sin dato,sin dato,sin dato,News,Hulu
11133,11133,Showtime Championship Boxing: Lopez vs. Salido...,Movie,2011,sin dato,sin dato,sin dato,sin dato,Sports,Hulu
11155,11155,BELLATOR MMA: Kongo vs. Johnson 2,Movie,2020,sin dato,sin dato,sin dato,sin dato,Sports,Hulu
11158,11158,In the Crease,Movie,2020,sin dato,sin dato,sin dato,sin dato,Sports,Hulu
...,...,...,...,...,...,...,...,...,...,...
14077,14077,Packed to the Rafters,Movie,2008,sin dato,sin dato,sin dato,sin dato,"Comedy, Drama, International",Hulu
14111,14111,Amy Winehouse: A Final Goodbye,Movie,2011,sin dato,sin dato,sin dato,sin dato,"Documentaries, Music",Hulu
19732,19732,Louis C.K. 2017,Movie,2017,Louis C.K.,sin dato,sin dato,sin dato,Movies,Netflix
19985,19985,Louis C.K.: Hilarious,Movie,2010,Louis C.K.,sin dato,sin dato,sin dato,Movies,Netflix
20004,20004,Louis C.K.: Live at the Comedy Store,Movie,2015,Louis C.K.,sin dato,sin dato,sin dato,Movies,Netflix

In [12]:
#con esto subo mis dataframes a workbencha sql para visualizar los datos cuando lo necesito

# from sqlalchemy import create_engine
# engine = create_engine('mysql+pymysql://root:root@localhost/pi1')
# df_unificado.to_sql('peliculas',con=engine,index=False,if_exists='replace')

In [13]:
df_unificado['duracion_minOSeason'].loc[df_unificado['duracion_minOSeason'] == 'Seasons'] = 'Season'

C:\Users\Danti\AppData\Local\Temp\ipykernel_14856\1440896641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['duracion_minOSeason'].loc[df_unificado['duracion_minOSeason'] == 'Seasons'] = 'Season'

In [14]:
#trasformo los que dicen 'Seasons' a 'Season' para que sea mas facil de manejar despues
df_unificado.loc[df_unificado['duracion_minOSeason'] == 'Seasons']['duracion_minOSeason']

Series([], Name: duracion_minOSeason, dtype: object)

In [15]:
#paso todas la columnas excepto el elenco y los nombres de las peliculas a minusculas para que sea mas facil de manejar
df_unificado['clasificacion'] = df_unificado['clasificacion'].str.lower()
df_unificado['duracion_minOSeason'] = df_unificado['duracion_minOSeason'].str.lower()
df_unificado['lista_de_generos'] = df_unificado['lista_de_generos'].str.lower()
df_unificado['plataforma'] = df_unificado['plataforma'].str.lower()

In [16]:
df_unificado

,indice,titulo,clasificacion,fecha_de_estreno,elenco,duracion,duracion_cantidad,duracion_minOSeason,lista_de_generos,plataforma
0,0,The Grand Seduction,movie,2014,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",113 min,113,min,"comedy, drama",amazon
1,1,Take Care Good Night,movie,2018,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",110 min,110,min,"drama, international",amazon
2,2,Secrets of Deception,movie,2017,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",74 min,74,min,"action, drama, suspense",amazon
3,3,Pink: Staying True,movie,2014,"Interviews with: Pink, Adele, Beyoncé, Britney...",69 min,69,min,documentary,amazon
4,4,Monster Maker,movie,1989,"Harry Dean Stanton, Kieran O'Brien, George Cos...",45 min,45,min,"drama, fantasy",amazon
...,...,...,...,...,...,...,...,...,...,...
22993,22993,Zodiac,movie,2007,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",158 min,158,min,"cult movies, dramas, thrillers",netflix
22994,22994,Zombie Dumb,tv show,2018,sin dato,2 Seasons,2,season,"kids' tv, korean tv shows, tv comedies",netflix
22995,22995,Zombieland,movie,2009,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",88 min,88,min,"comedies, horror movies",netflix
22996,22996,Zoom,movie,2006,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",88 min,88,min,"children & family movies, comedies",netflix
22997,22997,Zubaan,movie,2015,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",111 min,111,min,"dramas, international movies, music & musicals",netflix

In [17]:
df_unificado.to_csv(r'Datasets/data_series_movies.csv',index=False)